version: '2'
services:
    meteringsvc-app:
        image: meteringsvc
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://meteringsvc-postgresql:5432/meteringsvc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    meteringsvc-postgresql:
        extends:
            file: postgresql.yml
            service: meteringsvc-postgresql
